#+title: Help & Info
#+slug: help

* Instructors

There are 3 instructors for this course:

- [[https://marie-helene-burle.netlify.com][Marie-Helene (Marie) Burle]], from [[https://westgrid.ca][WestGrid]] and [[https://computecanada.ca][Compute Canada]]
- Grace Fishbein, from [[https://www.ace-net.ca/][ACENET]] and [[https://computecanada.ca][Compute Canada]]
- Lydia Vermeyden, from [[https://www.ace-net.ca/][ACENET]] and [[https://computecanada.ca][Compute Canada]]

* Schedule

***** Day 1

9:00 - 9:15am		Introductions and Course Plan \\
9:15 - 11:00am 	Command Line: http://swcarpentry.github.io/shell-novice/ \\
Lessons 1, 2 and 3 \\
11:00 - 11:15am 	Break \\
11:15 - 1:00pm 	Intro to Python

***** Day 2

Dive into Python

***** Day 3

Project Boosters \\
Specialty Topics in Breakout rooms

* Software installation

You will need to install a number of software on your machine for this course:

- [[https://docs.anaconda.com/anaconda/install/][Anaconda]]. \\
  This will install Python and many Python packages and tools.
- Windows users only: [[https://gitforwindows.org/][Git for Windows]]. \\
  We will not use Git in this workshop, but this software comes with a Bash emulation and we will use Bash a little. Linux and MacOS users do not need to install this as they already have Bash on their system.
- Once you have a terminal and Anaconda installed, you will be able to install [[https://jupyter.org/install][JupyterLab]]. \\
  As this installation requires the use of the command line, if you have issues, we will help you with that one at the start of the course.
- A good text editor. \\
  Note that Microsoft Word and similar are not text editors. They are word processors, meaning that they add a lot of invisible formatting to the text you type. Notepad is a text editor, but it is too limited. \\
  Examples of free good text editors suitable for beginners are [[https://code.visualstudio.com/download][Visual Studio Code]], [[https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-windows][Atom]], [[https://notepad-plus-plus.org/downloads/][Notepad++]], [[https://www.sublimetext.com/3][Sublime Text]]. Once you have installed one, it would be a good idea to familiarize yourself with it a little bit.

* Resources
** Books

There are many books on Python, several of which can be accessed online for free, either directly, or through your university.

**** Books by O'Reilly

1. *Think Python*, 2nd Edition, by Allen B. Downey
2. *Python Pocket Reference*, 5th Edition, by Mark Lutz
3. *Introducing Python*, by Bill Lubanovic
4. *Python in a Nutshell*, 3rd Edition, by Alex Martelli, Anna Ravenscroft, and Steve Holden
5. *Learning Python*, 5th Edition, by Mark Lutz
6. *Python Cookbook*, 3rd Edition, by David Beazley and Brian K. Jones
7. *The Hitchhiker's Guide to Python*, by Kenneth Reitz and Tanya Schlusser
8. *Fluent Python*, by Luciano Ramalho
9. *High Performance Python*, by Micha Gorelick and Ian Ozsvald
10. *Web Scraping with Python*, by Ryan Mitchell
11. *Python Data Science Handbook*, by Jake VanderPlas
12. *Python for Data Analysis*, by Wes McKinney
13. *Foundations for Analytics with Python*, by Clinton W. Brownley
14. *Data Wrangling with Python*, by Jacquiline Kazil and Katharine Jarmul
15. *Data Visualization with Python and Javascript*, by Kyran Dale
16. *Natural Language Processing with Python*, by Steven Bird and Ewan Klein
17. *Thoughtful Machine Learning with Python*, by Matthew Kirk
18. *Python for Finance*, by Yves Hilpisch

**** Books by No Starch Press

1. *Automate the Boring Stuff with Python*, by Al Sweigart
2. *Python Crash Course*, by Eric Matthews
3. *Python Playground*, by Mahesh Venkitachalam
4. *Doing Math with Python*, by Amit Saha
5. *Invent Your Own Computer Games with Python*, by Al Sweigart

**** Other books

1. *Python Machine Learning*, by Sebastian Raschka
2. *Practical Programming: An Introduction to Computer Science Using Python 3*, by Paul Gries, Jennifer Campbell, and Jason Montojo
3. *Python for Dummies*, by Stef Maruch and Aahz Maruch
4. *Python Essential Reference*, 4th Edition, by David Beazley
5. *Head First Python*, by Paul Barry
6. *Python for Data Science for Dummies*, by John Paul Mueller and Luca Massaron
7. *Beginning Programming with Python for Dummies*, by John Paul Mueller
8. *Python for Everybody*, by Charles Severance

* Example scripts from past projects

You can find example scripts from past projects in [[https://drive.google.com/drive/u/1/folders/0AA-7dFhKj4DXUk9PVA][this Google Drive folder]].

Feel free to use some of the code to build your own project.
