#+title: Dive into Python—Part 2
#+subtitle: Lesson Notes
#+slug: notes_part2

{{<cor>}}Tuesday, June 15{{</cor>}}

{{<cgr>}}11:15 am–1:00 pm{{</cgr>}} \\
*Connection Details:* {{<a "https://us02web.zoom.us/j/87259243311?pwd=RlhnU2huTGFpTFhwN1p5ZnpXcWEvdz0" "Lesson Room Link">}}

* Our training JupyterHub

For this session and for all sessions tomorrow, you are welcome to use our training JupyterHub on which all Python packages are installed and where the data is already downloaded. It will make getting setup a lot easier and faster.

To access the JupyterHub, you will need a username and password that I will give you in this course and you can find instructions in {{<a "https://dhsi-2021.netlify.app/help/#headline-22" "our help page">}}.

The username and password will remain valid for the entire week, so write them down somewhere and keep them at hand.
* Introduction to Pandas

For this section, we will use the Covid-19 data from the {{<a "https://github.com/CSSEGISandData/COVID-19" "Johns Hopkins University CSSE repository.">}} I last accessed this database on Saturday, so the last day of data we will use is June 12, 2021.

You can visualize this data in {{<a "https://www.arcgis.com/apps/dashboards/bda7594740fd40299423467b48e9ecf6" "a dashboard">}} created by the Johns Hopkins University Center for Systems Science and Engineering.

I already uploaded the two files we will use onto our JupyterHub. They are at: ~/project/def-sponsor00/dhsi/covid_confirmed.csv~ and ~/project/def-sponsor00/dhsi/covid_dead.csv~.

For those who want to work on their own machine, those files are also in {{<a "https://drive.google.com/drive/u/1/folders/1A-geyO7vQ6gND61zHBukTJeWMr9-pBMy" "our GoogleDrive">}}. You can download them from there, but you will have to make sure to change the code to match the paths of the files on your machine when you read them into Python.

For reference, {{<a "https://pandas.pydata.org/docs/user_guide/index.html" "here">}} is a User Guide to pandas and {{<a "https://pandas.pydata.org/pandas-docs/stable/reference/index.html" "here">}} is the full documentation.

** Setup

First, we need to load packages and read in the data.

#+BEGIN_src python
# Load the pandas package and create a shorter name for it
import pandas as pd

# Read in data from a csv file
cases = pd.read_csv('/project/def-sponsor00/dhsi/covid_confirmed.csv')
#+END_src

** First look at the data

What does our data look like?

#+BEGIN_src python
# Print the data
cases   # When not using Jupyter, you must use: print(cases)

# Look at the first rows
cases.head()
cases.head(25)

# And the last rows
cases.tail()

# Names of rows and columns
cases.index
cases.columns

# Quick summary of the data
cases.describe()

# Data types of the various columns
cases.dtypes
#+END_src

** Number of cases per country by decreasing values

#+BEGIN_src python
# Let's get rid of the latitude and longitude to simplify our data
simple = cases.drop(columns=['Lat', 'Long'])
simple

# Some countries are split between several provinces or states
simple[simple.loc[:, 'Country/Region'] == 'Australia']

# Let's make the sum per countries for all the dates
totals = simple.groupby('Country/Region').sum()
totals

# Now, we can look at the totals for any date
totals.loc[:, '6/12/21']

# And we can order them by decreasing values
totals.loc[:, '6/12/21'].sort_values(ascending=False)
#+END_src

** Global totals

Now, what if we want to have the world totals for each day?

#+BEGIN_src python
# Calculate the columns totals
totals.sum()
#+END_src

{{<challenge>}}
<em>Try to work together to answer the following question.<br>
Help each other out and make it a team effort!</em>
<br>
<br>
How many people had <b>died</b> from Covid-19 in Venezuela by March 10, 2021?<br>
(according to the available data)
{{</challenge>}}
